# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Attribute' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attribute
  pod 'SnapKit' #, '~> 4.0.0'

  target 'AttributeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AttributeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
